[project]
name = "DLUtils"
version = "0.1.0"
description = "Utils package"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy<2",
    "pydicom"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
